add_feature reworking

diff --git a/scripts/add_feature b/scripts/add_feature
--- a/scripts/add_feature
+++ b/scripts/add_feature
@@ -1,9 +1,24 @@
 #!/bin/bash
 
+FEATURE="$1"
+FEATURES=$(git ls-remote --heads template | sed 's#.*refs/heads/##')
+
 if [ $# -ne 1 ]; then
-    echo "Usage: add_feature $(git ls-remote --heads template | sed 's#.*refs/heads/##')"
+    echo "Usage: add_feature $FEATURES"
+    return 1
+fi
+
+if ! echo "$FEATURES" | grep -q "$FEATURE"; then
+    echo "Error: '$FEATURE' is not a valid feature."
     return 1
 fi
 
 git fetch template
-git merge template/"$1"
+git merge template/"$FEATURE"
+composer install
+
+if [ "$FEATURE" -eq "stripe" ]; then
+    php artisan vendor:publish --tag="cashier-migrations"
+    php artisan migrate
+    php artisan vendor:publish --tag="cashier-config"
+fi
